### ISSUE TITLE
binascii padding error

### ISSUE THREAD

**Issue by xogium** [burningalchemist/solo1-cli-fix#1]
It appears I can't seem to remove credentials from solo after creating them. Listing works fine but removing breaks:

```
solo key credential rm ssh:test1234
PIN:
Traceback (most recent call last):
  File "/home/xogium/.solo/bin/solo", line 8, in <module>
    sys.exit(solo_cli())
             ^^^^^^^^^^
  File "/home/xogium/.solo/lib/python3.11/site-packages/click/core.py", line 1130, in __call__
    return self.main(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/xogium/.solo/lib/python3.11/site-packages/click/core.py", line 1055, in main
    rv = self.invoke(ctx)
         ^^^^^^^^^^^^^^^^
  File "/home/xogium/.solo/lib/python3.11/site-packages/click/core.py", line 1657, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/xogium/.solo/lib/python3.11/site-packages/click/core.py", line 1657, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/xogium/.solo/lib/python3.11/site-packages/click/core.py", line 1657, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/xogium/.solo/lib/python3.11/site-packages/click/core.py", line 1404, in invoke
    return ctx.invoke(self.callback, **ctx.params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/xogium/.solo/lib/python3.11/site-packages/click/core.py", line 760, in invoke
    return __callback(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/xogium/.solo/lib/python3.11/site-packages/solo/cli/key.py", line 590, in cred_rm
    cred = {"id": base64.b64decode(credential_id), "type": "public-key"}
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/base64.py", line 88, in b64decode
    return binascii.a2b_base64(s, strict_mode=validate)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
binascii.Error: Incorrect padding
```

Do you think there could be a fix for this?

**Comment by xogium** [comment]
I tried with multiple python versions, even down to 3.8, and it breaks just the same. So either this is a dependency that breaks, either something on my system has changed to make this fail, but I have no idea what.

FWIW I run archlinux.

**Comment by burningalchemist** [comment]
Hey @xogium, I'll have a look, stay tuned. 👍

**Comment by burningalchemist** [comment]
Hey @xogium, I see the command you're using might be incorrect. The argument we pass in is Credential ID (you can retrieve it from `solo1 key credential ls`), so the base64 string is expected instead of `ssh:openssh` or smth. Check my example:
```
Relying Party       Username            Credential ID
-----------------------------------------------------
ssh:                openssh             [REDACTED]
```

Let me know if it worked out? 

I also learnt that I cannot run `make-credential` anymore, I'll try to see what we can do here too. :)

UPD: fixed along with some other commands. I'll post some new patches to this repo soon 👍

**Comment by xogium** [comment]
Oh. For some reason, this was in no way obvious to me...

Still, the program should catch that sort of errors, shouldn't it?

**Comment by burningalchemist** [comment]
Yeah, agreed! I made a patch to return a more descriptive message on the wrong input. 😃👍

I'll commit it soon. I also made the other commands work with Fido2 v1.0+ and disabled incompatible ones (sign-file and probe don't work for regular solo1 dongles.

It also looks to me solo1 is EOL, nobody maintains it anymore. 🤷‍♂️ It still works fine for me, though.

**Comment by burningalchemist** [comment]
@xogium JFYI, I've added the patch with remaining changes. 👍
